server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:\ProgramData\promtail\positions.yaml

clients:
  - url: http://192.168.100.138:3100/loki/api/v1/push

scrape_configs:
  - job_name: windows-security
    windows_events:
      eventlog_name: Security
      xpath_query: "*"
      bookmark_path: C:\ProgramData\promtail\bookmarks\security.xml
      labels:
        job: windows-security
        host: jam-w11-01

  - job_name: windows-system
    windows_events:
      eventlog_name: System
      xpath_query: "*"
      bookmark_path: C:\ProgramData\promtail\bookmarks\system.xml
      labels:
        job: windows-system
        host: jam-w11-01

  - job_name: windows-application
    windows_events:
      eventlog_name: Application
      xpath_query: "*"
      bookmark_path: C:\ProgramData\promtail\bookmarks\application.xml
      labels:
        job: windows-application
        host: jam-w11-01
